### ISSUE TITLE
Date format messes the sorting by date

### ISSUE THREAD

**Issue by Deznait** [SLOKnightfall/CraftersRecieptBook#2]
Hi! there's a small issue with the "Date" column. As it's formatted in the american style of month/day/year, if you try sorting by this column, it goes in a weird order: 
![imagen](https://user-images.githubusercontent.com/3739964/216597743-c938d7f5-f514-4441-91af-ebf85274187c.png)

In the picture if want it to sort descending by date, but first it shows the crafts from January and then the ones from February, and the days are correctly sorting descending,

I think that it's better to change the ISO format of year/month/date, or change the sorting method.

**Comment by SLOKnightfall** [comment]
Thanks for the report.  There was a bug where it was comparing the years twice instead of the year and then the month.  Should be fixed in the next update.
